repos:
  - repo: https://github.com/pre-commit/mirrors-eslint
    rev: ""
    hooks:
      - id: eslint
        files: \.[jt]sx?$ # *.js, *.jsx, *.ts and *.tsx
        types: [file]
  - repo: https://github.com/pre-commit/mirrors-autopep8
    rev: "" # Use the sha / tag you want to point at
    hooks:
      - id: autopep8
  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: "" # Use the sha / tag you want to point at
    hooks:
      - id: prettier
        additional_dependencies:
          - prettier@2.1.2
          - "@prettier/plugin-xml@0.12.0"
  - repo: https://github.com/pre-commit/pygrep-hooks
    rev: v1.10.0 # Use the ref you want to point at
    hooks:
      - id: python-use-type-annotations
    # ...
  - repo: https://github.com/PyCQA/pylint
    rev: "" # Use the sha / tag you want to point at
    hooks:
      - id: pylint
  - repo: https://github.com/PyCQA/flake8
    rev: "" # Use the sha / tag you want to point at
    hooks:
      - id: flake8
  - repo: https://github.com/PyCQA/bandit
    rev: "" # Use the sha / tag you want to point at
    hooks:
      - id: bandit
  - repo: https://github.com/PyCQA/isort
    rev: "" # Use the sha / tag you want to point at
    hooks:
      - id: isort
