repos:
  - repo: https://github.com/pre-commit/mirrors-eslint
    rev: "v8.42.0"
    hooks:
      - id: eslint
        files: \.[jt]sx?$
        types: [file]
  - repo: https://github.com/pre-commit/mirrors-autopep8
    rev: "v2.0.2" # Use the sha / tag you want to point at
    hooks:
      - id: autopep8
  - repo: https://github.com/PyCQA/isort
    rev: "5.12.0" # Use the sha / tag you want to point at
    hooks:
      - id: isort
  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: "v2.3.2" # Use the sha / tag you want to point at
    hooks:
      - id: prettier
        additional_dependencies:
          - prettier@2.1.2
          - "@prettier/plugin-xml@0.12.0"
  - repo: https://github.com/pre-commit/pygrep-hooks
    rev: v1.10.0 # Use the ref you want to point at
    hooks:
      - id: python-use-type-annotations
    # ...
  # - repo: https://github.com/psf/black
  #   rev: "23.3.0" # Use the sha / tag you want to point at
  #   hooks:
  #     - id: black
  #       language_version: python3.10
  #       args: [--line-length=100]
  - repo: https://github.com/PyCQA/pylint
    rev: "v3.0.0a6" # Use the sha / tag you want to point at
    hooks:
      - id: pylint
        args:
          [
            --disable=C0114,
            --disable=E0401,
            --disable=C0115,
            --disable=R0903,
            --disable=C0116,
            --disable=C0103,
            --disable=C0415,
          ]
  - repo: https://github.com/PyCQA/flake8
    rev: "6.0.0" # Use the sha / tag you want to point at
    hooks:
      - id: flake8
        name: Flake8
        entry: flake8
        language: python
        types: [python]
        args: [--ignore=E501]
        additional_dependencies: ["flake8"]
  - repo: https://github.com/PyCQA/bandit
    rev: "1.7.5" # Use the sha / tag you want to point at
    hooks:
      - id: bandit
