# Generated by Django 3.2.23 on 2024-02-07 20:30

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("post", "0006_trends"),
    ]

    operations = [
        migrations.RenameField(
            model_name="trends",
            old_name="hash_tag",
            new_name="hashtag",
        ),
    ]
