# Generated by Django 3.2.12 on 2024-01-08 11:58

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_user_friends_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='friendrequest',
            name='rejection_count',
            field=models.IntegerField(default=0, validators=[
                                      django.core.validators.MaxValueValidator(3)]),
        ),
    ]
