# Generated by Django 3.2.12 on 2024-01-10 07:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("account", "0006_friendrequest_rejection_count"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="posts_count",
            field=models.IntegerField(default=0),
        ),
    ]
