RESPONSE_STATUS_API = "status"
RESPONSE_MSG_API = "msg"
RESPONSE_STATE_API = "resp_state"
API_RESPONSE_OBJ = {
    RESPONSE_STATUS_API: False,
    RESPONSE_MSG_API: "TODO",
}
APPLICATION_JSON_DATA_TYPE = "application/json"
